In [41]:
import pandas as pd

In [42]:
import pandas as pd

sales_wide = pd.DataFrame({
    "Region": ["Accra", "Kumasi"],
    "2022": [5000, 4000],
    "2023": [7000, 6000],
    "2024": [8000, 7500],
    "2023": [5000,4000],
    "2023": [8000, 6000],
})

print(sales_wide)

   Region  2022  2023  2024
0   Accra  5000  8000  8000
1  Kumasi  4000  6000  7500

In [43]:
sales_long = pd.melt(
    sales_wide,
    id_vars=["Region"],
    var_name="Year",
    value_name="Sales"
).reset_index()

print(sales_long)

   index  Region  Year  Sales
0      0   Accra  2022   5000
1      1  Kumasi  2022   4000
2      2   Accra  2023   8000
3      3  Kumasi  2023   6000
4      4   Accra  2024   8000
5      5  Kumasi  2024   7500

In [47]:
sales_longsales_long = pd.melt(
    sales_wide,
    id_vars=["Region"],
    var_name="Year",
    value_name="Sales"
).reset_index()

print(sales_long)

   index  Region  Year  Sales
0      0   Accra  2022   5000
1      1  Kumasi  2022   4000
2      2   Accra  2023   8000
3      3  Kumasi  2023   6000
4      4   Accra  2024   8000
5      5  Kumasi  2024   7500

In [48]:
#Ghana Example: SHS Performance Data
grades = pd.DataFrame({
    "Student": ["Ama", "Kojo"],
    "Math": [85, 78],
    "Science": [90, 88],
    "English": [75, 80]
})
grades

  Student  Math  Science  English
0     Ama    85       90       75
1    Kojo    78       88       80

In [49]:

grades_wide = grades_long.pivot_table(
    index="Student",
    columns="Subject",
    values="Score",
    aggfunc="mean"
)

print(grades_wide)

NameError: name 'grades_long' is not defined

In [ ]:
hospital = pd.DataFrame ({
    "patient":["p001","p002"],
    "jan_BP":[120,130],
    "feb_BP":[125,135], 
    "mar_BP":[122,132]
})
hospital

  patient  jan_BP  feb_BP  mar_BP
0    p001     120     125     122
1    p002     130     135     132

In [ ]:
#solutions

hospital_wide = pd(
    hospital,
    id_vars=["patient"],
    var_name="month",
    value_name="Blood Pressure"
) 
hospital_long

TypeError: 'module' object is not callable

In [ ]:
hospital_long.groupby("patient")["blood_pressure"].agg