Importing messy data to be cleaned

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("student_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'student_data.csv'

In [ ]:
df

,student_id,name,gender,class,math_score,english_score,science_score,history_score,dob,tuition_paid,tuition_amount,contact,address,house
0,201,james kwame,Male,Grade 9,78.0,72.0,80.0,68.0,2008-05-14,Yes,"GHS 1,200",0241234567,Accra,Adenta
1,202,Abena Mensah,female,grade 10,85.0,88.0,NaN,74.0,2007-11-30,no,"GHS 1,500",0557654321,kumasi,Adum
2,203,Kofi Adu,M,Grade 9,92.0,95.0,88.0,NaN,2008-03-22,YES,"GHS 1,200",024-111-2222,TEMA,Community 5
3,204,Ama Boateng,Female,GRADE 11,NaN,81.0,76.0,85.0,2006-07-18,No,"GHS 2,000",0201234567,Accra,Lapaz
4,205,KWEKU ASANTE,MALE,Grade 10,67.0,74.0,70.0,71.0,2007-09-05,yes,"GHS 1,500",055 987 6543,Takoradi,Effia
5,203,james kwame,Male,Grade 9,78.0,72.0,80.0,68.0,2008-05-14,Yes,"GHS 1,200",0241234567,Accra,Adenta
6,206,Efua Darko,F,grade 11,110.0,89.0,85.0,90.0,2006-12-01,NO,"GHS 2,000",0278765432,KUMASI,Nhyiaeso
7,207,Yaw Tetteh,male,Grade 9,74.0,NaN,69.0,65.0,2008-01-17,yes,"GHS 1,200",NaN,tema,community 5
8,208,Akosua,Female,Grade 10,88.0,93.0,NaN,NaN,2007-04-25,No,"GHS 1,500",0241122334,accra,LAPAZ
9,209,Kojo Frimpong,FEMALE,GRADE 9,NaN,77.0,82.0,80.0,2008-08-10,YES,"GHS 1,200",0559988776,Takoradi,Effia
10,210,Adwoa Sarpong,female,Grade 11,91.0,85.0,90.0,77.0,2006-05-30,no,"GHS 2,000",027-444-5555,Kumasi,Adum
11,211,BISMARK OWUSU,Male,Grade 10,55.0,61.0,64.0,NaN,14/03/2007,Yes,"GHS 1,500",024 333 4444,ACCRA,ADENTA
12,212,nana ama asante,F,GRADE 9,76.0,NaN,78.0,69.0,22/09/2008,NO,"GHS 1,200",0201122334,Tema,nhyiaeso
13,213,Kwabena Poku,MALE,grade 11,NaN,79.0,85.0,83.0,2007-06-15,yes,"GHS 2,000",027-222-3333,kumasi,Adum
14,214,Serwa Mensah,female,Grade 10,89.0,92.0,NaN,78.0,05/11/2006,No,"GHS 1,500",NaN,Accra,Lapaz
15,215,Fiifi Ankrah,m,GRADE 9,95.0,88.0,92.0,91.0,2008-02-28,YES,"GHS 1,200",0559876543,TAKORADI,EFFIA
16,216,ABENA KYEI,Female,grade 10,43.0,NaN,57.0,55.0,17/07/2007,no,"GHS 2,000",024-567-8901,accra,adenta
17,217,kofi boateng,Male,Grade 11,110.0,73.0,75.0,NaN,2006-10-09,Yes,"GHS 1,500",0207654321,Kumasi,Community 5
18,218,Esi Quaye,f,GRADE 9,67.0,85.0,88.0,76.0,30/04/2008,NO,GHS 1200,055 111 2222,TEMA,NHYIAESO
19,219,Kwame Asare,MALE,grade 10,NaN,91.0,70.0,88.0,2007-12-21,yes,"GHS 2,000",NaN,accra,adenta
20,220,AKUA DARKO,Female,Grade 11,84.0,66.0,NaN,70.0,11/08/2006,No,GHS1500,0278899001,takoradi,Lapaz
21,221,Yaw Antwi,male,GRADE 9,72.0,78.0,83.0,NaN,2008-07-03,YES,"GHS 1,200",024 444 5555,Accra,Effia
22,222,ADWOA FRIMPONG,FEMALE,grade 10,NaN,84.0,77.0,81.0,25/01/2007,no,GHS 2000,0201234321,KUMASI,ADUM
23,223,kojo mensah,M,Grade 11,91.0,NaN,91.0,74.0,2006-09-14,Yes,"GHS 1,500",027-888-9999,tema,community 5
24,224,Ama Tetteh,female,GRADE 9,58.0,69.0,NaN,67.0,08/06/2008,NO,"GHS 1,200",0559871234,ACCRA,Adenta
25,225,Kweku Adu,Male,grade 10,88.0,90.0,86.0,NaN,2007-03-19,yes,"GHS 2,000",NaN,Kumasi,LAPAZ
26,226,NANA OWUSU,MALE,Grade 11,110.0,75.0,68.0,92.0,22/11/2006,No,GHS 1500,024-999-0000,Takoradi,nhyiaeso
27,227,efua kyei,Female,GRADE 9,NaN,88.0,79.0,63.0,2008-04-11,YES,"GHS 1,200",0208877665,ACCRA,Effia
28,228,Bismark Quaye,m,grade 10,77.0,NaN,95.0,85.0,15/07/2007,no,"GHS 2,000",055 222 3333,kumasi,ADENTA
29,229,Serwa Ankrah,f,Grade 11,65.0,71.0,NaN,79.0,03/02/2006,Yes,GHS1200,NaN,Tema,adum
30,230,KOFI ASANTE,male,GRADE 9,93.0,95.0,88.0,NaN,2008-09-27,NO,"GHS 1,500",0271122334,accra,Community 5

In [ ]:
print(df["name"].tolist())
df["name"] = df["name"].str.strip().str.replace(r"\s+", " ", regex=True).str.title()
print(df["name"].tolist())

['james kwame', 'Abena  Mensah', ' Kofi Adu', 'Ama Boateng', 'KWEKU ASANTE', 'james kwame', 'Efua Darko ', 'Yaw Tetteh', 'Akosua', 'Kojo Frimpong', 'Adwoa  Sarpong', 'BISMARK OWUSU', 'nana ama asante', 'Kwabena  Poku', ' Serwa Mensah', 'Fiifi Ankrah', 'ABENA KYEI', 'kofi  boateng', 'Esi Quaye ', ' Kwame Asare', 'AKUA DARKO', 'Yaw  Antwi', 'ADWOA FRIMPONG', 'kojo  mensah', 'Ama Tetteh ', ' Kweku Adu', 'NANA OWUSU', 'efua  kyei', 'Bismark Quaye ', ' Serwa Ankrah', 'KOFI ASANTE']
['James Kwame', 'Abena Mensah', 'Kofi Adu', 'Ama Boateng', 'Kweku Asante', 'James Kwame', 'Efua Darko', 'Yaw Tetteh', 'Akosua', 'Kojo Frimpong', 'Adwoa Sarpong', 'Bismark Owusu', 'Nana Ama Asante', 'Kwabena Poku', 'Serwa Mensah', 'Fiifi Ankrah', 'Abena Kyei', 'Kofi Boateng', 'Esi Quaye', 'Kwame Asare', 'Akua Darko', 'Yaw Antwi', 'Adwoa Frimpong', 'Kojo Mensah', 'Ama Tetteh', 'Kweku Adu', 'Nana Owusu', 'Efua Kyei', 'Bismark Quaye', 'Serwa Ankrah', 'Kofi Asante']

In [ ]:
df["gender"] = df["gender"].str.title()
print(df["gender"].tolist())

['Male', 'Female', 'M', 'Female', 'Male', 'Male', 'F', 'Male', 'Female', 'Female', 'Female', 'Male', 'F', 'Male', 'Female', 'M', 'Female', 'Male', 'F', 'Male', 'Female', 'Male', 'Female', 'M', 'Female', 'Male', 'Male', 'Female', 'M', 'F', 'Male']

In [ ]:
df["class"] = df["class"].str.title()
print(df["class"])

0      Grade 9
1     Grade 10
2      Grade 9
3     Grade 11
4     Grade 10
5      Grade 9
6     Grade 11
7      Grade 9
8     Grade 10
9      Grade 9
10    Grade 11
11    Grade 10
12     Grade 9
13    Grade 11
14    Grade 10
15     Grade 9
16    Grade 10
17    Grade 11
18     Grade 9
19    Grade 10
20    Grade 11
21     Grade 9
22    Grade 10
23    Grade 11
24     Grade 9
25    Grade 10
26    Grade 11
27     Grade 9
28    Grade 10
29    Grade 11
30     Grade 9
Name: class, dtype: str

In [ ]:
df.dtypes

student_id          int64
name                  str
gender                str
class                 str
math_score        float64
english_score     float64
science_score     float64
history_score     float64
dob                   str
tuition_paid          str
tuition_amount        str
contact               str
address               str
house                 str
dtype: object

In [ ]:
median_math_score = df["math_score"].median()
df["math_score"] = df["math_score"].fillna(median_math_score)

In [ ]:
median_english_score = df["english_score"].median()
df["english_score"] = df["english_score"].fillna(median_english_score)

In [ ]:
median_science_score = df["science_score"].median()
df["science_score"] = df["science_score"].fillna(median_science_score)

print(df["science_score"])

0     80.0
1     80.0
2     88.0
3     76.0
4     70.0
5     80.0
6     85.0
7     69.0
8     80.0
9     82.0
10    90.0
11    64.0
12    78.0
13    85.0
14    80.0
15    92.0
16    57.0
17    75.0
18    88.0
19    70.0
20    80.0
21    83.0
22    77.0
23    91.0
24    80.0
25    86.0
26    68.0
27    79.0
28    95.0
29    80.0
30    88.0
Name: science_score, dtype: float64

In [ ]:
median_histry_score = df["history_score"].median()
df["history_score"] = df["history_score"].fillna(median_histry_score)

print(df["history_score"])

0     68.0
1     74.0
2     76.5
3     85.0
4     71.0
5     68.0
6     90.0
7     65.0
8     76.5
9     80.0
10    77.0
11    76.5
12    69.0
13    83.0
14    78.0
15    91.0
16    55.0
17    76.5
18    76.0
19    88.0
20    70.0
21    76.5
22    81.0
23    74.0
24    67.0
25    76.5
26    92.0
27    63.0
28    85.0
29    79.0
30    76.5
Name: history_score, dtype: float64

In [ ]:
df["dob"] = df["dob"].str.replace("-", "/")

In [ ]:
df["tuition_paid"] = df["tuition_paid"].str.title()
print(df["tuition_paid"].tolist())

['Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No']

In [ ]:
df["contact"] = df["contact"].str.replace("-", "").str.replace(" ", "")
df["contact"] = df["contact"].fillna("0024377522")
# df["contact"] = df["contact"].astype(int)
df["contact"]

0     0241234567
1     0557654321
2     0241112222
3     0201234567
4     0559876543
5     0241234567
6     0278765432
7     0024377522
8     0241122334
9     0559988776
10    0274445555
11    0243334444
12    0201122334
13    0272223333
14    0024377522
15    0559876543
16    0245678901
17    0207654321
18    0551112222
19    0024377522
20    0278899001
21    0244445555
22    0201234321
23    0278889999
24    0559871234
25    0024377522
26    0249990000
27    0208877665
28    0552223333
29    0024377522
30    0271122334
Name: contact, dtype: str

In [ ]:
df.dtypes

student_id          int64
name                  str
gender                str
class                 str
math_score        float64
english_score     float64
science_score     float64
history_score     float64
dob                   str
tuition_paid          str
tuition_amount        str
contact               str
address               str
house                 str
dtype: object

In [ ]:
df["address"] = df["address"].str.title() 

print(df["address"].tolist())

['Accra', 'Kumasi', 'Tema', 'Accra', 'Takoradi', 'Accra', 'Kumasi', 'Tema', 'Accra', 'Takoradi', 'Kumasi', 'Accra', 'Tema', 'Kumasi', 'Accra', 'Takoradi', 'Accra', 'Kumasi', 'Tema', 'Accra', 'Takoradi', 'Accra', 'Kumasi', 'Tema', 'Accra', 'Kumasi', 'Takoradi', 'Accra', 'Kumasi', 'Tema', 'Accra']

In [ ]:
df["house"] = df["house"].str.title()
print(df["house"].tolist())

['Adenta', 'Adum', 'Community 5', 'Lapaz', 'Effia', 'Adenta', 'Nhyiaeso', 'Community 5', 'Lapaz', 'Effia', 'Adum', 'Adenta', 'Nhyiaeso', 'Adum', 'Lapaz', 'Effia', 'Adenta', 'Community 5', 'Nhyiaeso', 'Adenta', 'Lapaz', 'Effia', 'Adum', 'Community 5', 'Adenta', 'Lapaz', 'Nhyiaeso', 'Effia', 'Adenta', 'Adum', 'Community 5']

In [ ]:
print(df)

    student_id             name  gender     class  math_score  english_score  \
0          201      James Kwame    Male   Grade 9        78.0           72.0
1          202     Abena Mensah  Female  Grade 10        85.0           88.0
2          203         Kofi Adu       M   Grade 9        92.0           95.0
3          204      Ama Boateng  Female  Grade 11        84.0           81.0
4          205     Kweku Asante    Male  Grade 10        67.0           74.0
5          203      James Kwame    Male   Grade 9        78.0           72.0
6          206       Efua Darko       F  Grade 11       110.0           89.0
7          207       Yaw Tetteh    Male   Grade 9        74.0           82.5
8          208           Akosua  Female  Grade 10        88.0           93.0
9          209    Kojo Frimpong  Female   Grade 9        84.0           77.0
10         210    Adwoa Sarpong  Female  Grade 11        91.0           85.0
11         211    Bismark Owusu    Male  Grade 10        55.0           61.0
12         212  Nana Ama Asante       F   Grade 9        76.0           82.5
13         213     Kwabena Poku    Male  Grade 11        84.0           79.0
14         214     Serwa Mensah  Female  Grade 10        89.0           92.0
15         215     Fiifi Ankrah       M   Grade 9        95.0           88.0
16         216       Abena Kyei  Female  Grade 10        43.0           82.5
17         217     Kofi Boateng    Male  Grade 11       110.0           73.0
18         218        Esi Quaye       F   Grade 9        67.0           85.0
19         219      Kwame Asare    Male  Grade 10        84.0           91.0
20         220       Akua Darko  Female  Grade 11        84.0           66.0
21         221        Yaw Antwi    Male   Grade 9        72.0           78.0
22         222   Adwoa Frimpong  Female  Grade 10        84.0           84.0
23         223      Kojo Mensah       M  Grade 11        91.0           82.5
24         224       Ama Tetteh  Female   Grade 9        58.0           69.0
25         225        Kweku Adu    Male  Grade 10        88.0           90.0
26         226       Nana Owusu    Male  Grade 11       110.0           75.0
27         227        Efua Kyei  Female   Grade 9        84.0           88.0
28         228    Bismark Quaye       M  Grade 10        77.0           82.5
29         229     Serwa Ankrah       F  Grade 11        65.0           71.0
30         230      Kofi Asante    Male   Grade 9        93.0           95.0

    science_score  history_score         dob tuition_paid tuition_amount  \
0            80.0           68.0  2008/05/14          Yes      GHS 1,200
1            80.0           74.0  2007/11/30           No      GHS 1,500
2            88.0           76.5  2008/03/22          Yes      GHS 1,200
3            76.0           85.0  2006/07/18           No      GHS 2,000
4            70.0           71.0  2007/09/05          Yes      GHS 1,500
5            80.0           68.0  2008/05/14          Yes      GHS 1,200
6            85.0           90.0  2006/12/01           No      GHS 2,000
7            69.0           65.0  2008/01/17          Yes      GHS 1,200
8            80.0           76.5  2007/04/25           No      GHS 1,500
9            82.0           80.0  2008/08/10          Yes      GHS 1,200
10           90.0           77.0  2006/05/30           No      GHS 2,000
11           64.0           76.5  14/03/2007          Yes      GHS 1,500
12           78.0           69.0  22/09/2008           No      GHS 1,200
13           85.0           83.0  2007/06/15          Yes      GHS 2,000
14           80.0           78.0  05/11/2006           No      GHS 1,500
15           92.0           91.0  2008/02/28          Yes      GHS 1,200
16           57.0           55.0  17/07/2007           No      GHS 2,000
17           75.0           76.5  2006/10/09          Yes      GHS 1,500
18           88.0           76.0  30/04/2008           No       GHS 1200
19           70.0           88.0  2007/12/21          Yes      GHS 2,000
20           80.0           70.0  11/08/2006           No        GHS1500
21           83.0           76.5  2008/07/03          Yes      GHS 1,200
22           77.0           81.0  25/01/2007           No       GHS 2000
23           91.0           74.0  2006/09/14          Yes      GHS 1,500
24           80.0           67.0  08/06/2008           No      GHS 1,200
25           86.0           76.5  2007/03/19          Yes      GHS 2,000
26           68.0           92.0  22/11/2006           No       GHS 1500
27           79.0           63.0  2008/04/11          Yes      GHS 1,200
28           95.0           85.0  15/07/2007           No      GHS 2,000
29           80.0           79.0  03/02/2006          Yes        GHS1200
30           88.0           76.5  2008/09/27           No      GHS 1,500

       contact   address        house
0   0241234567     Accra       Adenta
1   0557654321    Kumasi         Adum
2   0241112222      Tema  Community 5
3   0201234567     Accra        Lapaz
4   0559876543  Takoradi        Effia
5   0241234567     Accra       Adenta
6   0278765432    Kumasi     Nhyiaeso
7   0024377522      Tema  Community 5
8   0241122334     Accra        Lapaz
9   0559988776  Takoradi        Effia
10  0274445555    Kumasi         Adum
11  0243334444     Accra       Adenta
12  0201122334      Tema     Nhyiaeso
13  0272223333    Kumasi         Adum
14  0024377522     Accra        Lapaz
15  0559876543  Takoradi        Effia
16  0245678901     Accra       Adenta
17  0207654321    Kumasi  Community 5
18  0551112222      Tema     Nhyiaeso
19  0024377522     Accra       Adenta
20  0278899001  Takoradi        Lapaz
21  0244445555     Accra        Effia
22  0201234321    Kumasi         Adum
23  0278889999      Tema  Community 5
24  0559871234     Accra       Adenta
25  0024377522    Kumasi        Lapaz
26  0249990000  Takoradi     Nhyiaeso
27  0208877665     Accra        Effia
28  0552223333    Kumasi       Adenta
29  0024377522      Tema         Adum
30  0271122334     Accra  Community 5

In [ ]:
print(df[df["name"].duplicated(keep=False)])
df

   student_id         name gender    class  math_score  english_score  \
0         201  James Kwame   Male  Grade 9        78.0           72.0
5         203  James Kwame   Male  Grade 9        78.0           72.0

   science_score  history_score         dob tuition_paid tuition_amount  \
0           80.0           68.0  2008/05/14          Yes      GHS 1,200
5           80.0           68.0  2008/05/14          Yes      GHS 1,200

      contact address   house
0  0241234567   Accra  Adenta
5  0241234567   Accra  Adenta

,student_id,name,gender,class,math_score,english_score,science_score,history_score,dob,tuition_paid,tuition_amount,contact,address,house
0,201,James Kwame,Male,Grade 9,78.0,72.0,80.0,68.0,2008/05/14,Yes,"GHS 1,200",0241234567,Accra,Adenta
1,202,Abena Mensah,Female,Grade 10,85.0,88.0,80.0,74.0,2007/11/30,No,"GHS 1,500",0557654321,Kumasi,Adum
2,203,Kofi Adu,M,Grade 9,92.0,95.0,88.0,76.5,2008/03/22,Yes,"GHS 1,200",0241112222,Tema,Community 5
3,204,Ama Boateng,Female,Grade 11,84.0,81.0,76.0,85.0,2006/07/18,No,"GHS 2,000",0201234567,Accra,Lapaz
4,205,Kweku Asante,Male,Grade 10,67.0,74.0,70.0,71.0,2007/09/05,Yes,"GHS 1,500",0559876543,Takoradi,Effia
5,203,James Kwame,Male,Grade 9,78.0,72.0,80.0,68.0,2008/05/14,Yes,"GHS 1,200",0241234567,Accra,Adenta
6,206,Efua Darko,F,Grade 11,110.0,89.0,85.0,90.0,2006/12/01,No,"GHS 2,000",0278765432,Kumasi,Nhyiaeso
7,207,Yaw Tetteh,Male,Grade 9,74.0,82.5,69.0,65.0,2008/01/17,Yes,"GHS 1,200",0024377522,Tema,Community 5
8,208,Akosua,Female,Grade 10,88.0,93.0,80.0,76.5,2007/04/25,No,"GHS 1,500",0241122334,Accra,Lapaz
9,209,Kojo Frimpong,Female,Grade 9,84.0,77.0,82.0,80.0,2008/08/10,Yes,"GHS 1,200",0559988776,Takoradi,Effia
10,210,Adwoa Sarpong,Female,Grade 11,91.0,85.0,90.0,77.0,2006/05/30,No,"GHS 2,000",0274445555,Kumasi,Adum
11,211,Bismark Owusu,Male,Grade 10,55.0,61.0,64.0,76.5,14/03/2007,Yes,"GHS 1,500",0243334444,Accra,Adenta
12,212,Nana Ama Asante,F,Grade 9,76.0,82.5,78.0,69.0,22/09/2008,No,"GHS 1,200",0201122334,Tema,Nhyiaeso
13,213,Kwabena Poku,Male,Grade 11,84.0,79.0,85.0,83.0,2007/06/15,Yes,"GHS 2,000",0272223333,Kumasi,Adum
14,214,Serwa Mensah,Female,Grade 10,89.0,92.0,80.0,78.0,05/11/2006,No,"GHS 1,500",0024377522,Accra,Lapaz
15,215,Fiifi Ankrah,M,Grade 9,95.0,88.0,92.0,91.0,2008/02/28,Yes,"GHS 1,200",0559876543,Takoradi,Effia
16,216,Abena Kyei,Female,Grade 10,43.0,82.5,57.0,55.0,17/07/2007,No,"GHS 2,000",0245678901,Accra,Adenta
17,217,Kofi Boateng,Male,Grade 11,110.0,73.0,75.0,76.5,2006/10/09,Yes,"GHS 1,500",0207654321,Kumasi,Community 5
18,218,Esi Quaye,F,Grade 9,67.0,85.0,88.0,76.0,30/04/2008,No,GHS 1200,0551112222,Tema,Nhyiaeso
19,219,Kwame Asare,Male,Grade 10,84.0,91.0,70.0,88.0,2007/12/21,Yes,"GHS 2,000",0024377522,Accra,Adenta
20,220,Akua Darko,Female,Grade 11,84.0,66.0,80.0,70.0,11/08/2006,No,GHS1500,0278899001,Takoradi,Lapaz
21,221,Yaw Antwi,Male,Grade 9,72.0,78.0,83.0,76.5,2008/07/03,Yes,"GHS 1,200",0244445555,Accra,Effia
22,222,Adwoa Frimpong,Female,Grade 10,84.0,84.0,77.0,81.0,25/01/2007,No,GHS 2000,0201234321,Kumasi,Adum
23,223,Kojo Mensah,M,Grade 11,91.0,82.5,91.0,74.0,2006/09/14,Yes,"GHS 1,500",0278889999,Tema,Community 5
24,224,Ama Tetteh,Female,Grade 9,58.0,69.0,80.0,67.0,08/06/2008,No,"GHS 1,200",0559871234,Accra,Adenta
25,225,Kweku Adu,Male,Grade 10,88.0,90.0,86.0,76.5,2007/03/19,Yes,"GHS 2,000",0024377522,Kumasi,Lapaz
26,226,Nana Owusu,Male,Grade 11,110.0,75.0,68.0,92.0,22/11/2006,No,GHS 1500,0249990000,Takoradi,Nhyiaeso
27,227,Efua Kyei,Female,Grade 9,84.0,88.0,79.0,63.0,2008/04/11,Yes,"GHS 1,200",0208877665,Accra,Effia
28,228,Bismark Quaye,M,Grade 10,77.0,82.5,95.0,85.0,15/07/2007,No,"GHS 2,000",0552223333,Kumasi,Adenta
29,229,Serwa Ankrah,F,Grade 11,65.0,71.0,80.0,79.0,03/02/2006,Yes,GHS1200,0024377522,Tema,Adum
30,230,Kofi Asante,Male,Grade 9,93.0,95.0,88.0,76.5,2008/09/27,No,"GHS 1,500",0271122334,Accra,Community 5

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      31 non-null     int64
 1   name            31 non-null     str
 2   gender          31 non-null     str
 3   class           31 non-null     str
 4   math_score      31 non-null     float64
 5   english_score   31 non-null     float64
 6   science_score   31 non-null     float64
 7   history_score   31 non-null     float64
 8   dob             31 non-null     str
 9   tuition_paid    31 non-null     str
 10  tuition_amount  31 non-null     str
 11  contact         31 non-null     str
 12  address         31 non-null     str
 13  house           31 non-null     str
dtypes: float64(4), int64(1), str(9)
memory usage: 3.5 KB

In [ ]:
df["tuition_amount"] = df["tuition_amount"].str.replace("GHS", "").str.replace(",", "")
df["tuition_amount"] = df["tuition_amount"].astype(int)
df["tuition_amount"].dtypes

dtype('int64')

In [ ]:
df["dob"] = pd.to_datetime(df["dob"], dayfirst=True, errors="coerce")

df["dob"] = df["dob"].dt.strftime("%Y/%-m/%-d")

df["dob"] = df["dob"].fillna(pd.Timestamp("2000/01/01"))

df["dob"] = pd.to_datetime(df["dob"])

df.dtypes

C:\Users\user\AppData\Local\Temp\ipykernel_8136\2466614747.py:1: UserWarning: Parsing dates in %Y/%m/%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["dob"] = pd.to_datetime(df["dob"], dayfirst=True, errors="coerce")

student_id                 int64
name                         str
gender                       str
class                        str
math_score               float64
english_score            float64
science_score            float64
history_score            float64
dob               datetime64[us]
tuition_paid                 str
tuition_amount             int64
contact                      str
address                      str
house                        str
dtype: object

In [ ]:
df["gender"] = df["gender"].replace({
    "M": "Male",
    "F": "Female"
})

df["gender"]

0       Male
1     Female
2       Male
3     Female
4       Male
5       Male
6     Female
7       Male
8     Female
9     Female
10    Female
11      Male
12    Female
13      Male
14    Female
15      Male
16    Female
17      Male
18    Female
19      Male
20    Female
21      Male
22    Female
23      Male
24    Female
25      Male
26      Male
27    Female
28      Male
29    Female
30      Male
Name: gender, dtype: str

In [ ]:
# Remove duplicates
df = df.drop_duplicates(subset=["name"])
# Fix scores > 100
df.loc[df["math_score"] > 100, "math_score"] = 100
# Handle fake DOB
# df.loc[df["dob"] == "2000/01/01", "dob"] = None
# Clean contact numbers
df["contact"] = df["contact"].str.replace("00243", "0", regex=False)
# 5. Find missing/short names
df[df["name"].str.split().str.len() < 2]
# Check inconsistencies
df.groupby("address")["house"].unique()

address
Accra                [Adenta, Lapaz, Effia, Community 5]
Kumasi      [Adum, Nhyiaeso, Community 5, Lapaz, Adenta]
Takoradi                        [Effia, Lapaz, Nhyiaeso]
Tema                       [Community 5, Nhyiaeso, Adum]
Name: house, dtype: object

In [ ]:
df.to_csv("clean.csv", index=False)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 30 entries, 0 to 30
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      30 non-null     int64
 1   name            30 non-null     str
 2   gender          30 non-null     str
 3   class           30 non-null     str
 4   math_score      30 non-null     float64
 5   english_score   30 non-null     float64
 6   science_score   30 non-null     float64
 7   history_score   30 non-null     float64
 8   dob             30 non-null     datetime64[us]
 9   tuition_paid    30 non-null     str
 10  tuition_amount  30 non-null     int64
 11  contact         30 non-null     str
 12  address         30 non-null     str
 13  house           30 non-null     str
dtypes: datetime64[us](1), float64(4), int64(2), str(7)
memory usage: 3.5 KB