In [69]:
import pandas as pd

In [70]:
df = pd.read_csv("format.csv")

In [71]:
print(df)

    Name  Age             Email  Country Salary
0  Isaac    17  isaac@email.com    Ghana   2000
1   John         john@email.com      USA   3000
2   mary    25   MARY@email.com       uk
3  Isaac    17  isaac@email.com    Ghana   2000
4    NaN    30     noemail@.com  Nigeria   4000
5  Peter   200      peter@email    Kenya   5000
6   Anna    22   anna@email.com            3500
7  Kwame   28   kwame@email.com    Ghana    NaN

In [72]:
print(df.isnull())

    Name   Age   Email  Country  Salary
0  False  False  False    False   False
1  False  False  False    False   False
2  False  False  False    False   False
3  False  False  False    False   False
4   True  False  False    False   False
5  False  False  False    False   False
6  False  False  False    False   False
7  False  False  False    False    True

In [73]:
print(df.isnull().sum())

Name       1
 Age       0
Email      0
Country    0
Salary     1
dtype: int64

In [74]:
print(df.duplicated())

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [75]:
print(df.duplicated().sum(),"Duplicates found")

1 Duplicates found

In [76]:
df.columns

Index(['Name', ' Age ', 'Email', 'Country', 'Salary'], dtype='str')

In [77]:
print(df)

    Name  Age             Email  Country Salary
0  Isaac    17  isaac@email.com    Ghana   2000
1   John         john@email.com      USA   3000
2   mary    25   MARY@email.com       uk
3  Isaac    17  isaac@email.com    Ghana   2000
4    NaN    30     noemail@.com  Nigeria   4000
5  Peter   200      peter@email    Kenya   5000
6   Anna    22   anna@email.com            3500
7  Kwame   28   kwame@email.com    Ghana    NaN

In [78]:
df = df.drop_duplicates()

In [11]:
print(df.duplicated().sum())

0

In [79]:
print(df.duplicated())

0    False
1    False
2    False
4    False
5    False
6    False
7    False
dtype: bool

In [80]:
print(df)

    Name  Age             Email  Country Salary
0  Isaac    17  isaac@email.com    Ghana   2000
1   John         john@email.com      USA   3000
2   mary    25   MARY@email.com       uk
4    NaN    30     noemail@.com  Nigeria   4000
5  Peter   200      peter@email    Kenya   5000
6   Anna    22   anna@email.com            3500
7  Kwame   28   kwame@email.com    Ghana    NaN

In [81]:
df.loc[4,"Name"] = "Kodjo"

In [82]:
print(df)

    Name  Age             Email  Country Salary
0  Isaac    17  isaac@email.com    Ghana   2000
1   John         john@email.com      USA   3000
2   mary    25   MARY@email.com       uk
4  Kodjo    30     noemail@.com  Nigeria   4000
5  Peter   200      peter@email    Kenya   5000
6   Anna    22   anna@email.com            3500
7  Kwame   28   kwame@email.com    Ghana    NaN

In [83]:
print(df.isnull().sum())

Name       0
 Age       0
Email      0
Country    0
Salary     1
dtype: int64

In [85]:
print(df)

    Name  Age             Email  Country Salary
0  Isaac    17  isaac@email.com    Ghana   2000
1   John         john@email.com      USA   3000
2   mary    25   MARY@email.com       uk
4  Kodjo    30     noemail@.com  Nigeria   4000
5  Peter   200      peter@email    Kenya   5000
6   Anna    22   anna@email.com            3500
7  Kwame   28   kwame@email.com    Ghana    NaN

In [86]:
df["Salary"] = pd.to_numeric(df["Salary"],errors="coerce")

df.loc[7,"Salary"] = 5300

In [87]:
print(df)

    Name  Age             Email  Country  Salary
0  Isaac    17  isaac@email.com    Ghana  2000.0
1   John         john@email.com      USA  3000.0
2   mary    25   MARY@email.com       uk     NaN
4  Kodjo    30     noemail@.com  Nigeria  4000.0
5  Peter   200      peter@email    Kenya  5000.0
6   Anna    22   anna@email.com           3500.0
7  Kwame   28   kwame@email.com    Ghana  5300.0

In [88]:
print(df.columns)

Index(['Name', ' Age ', 'Email', 'Country', 'Salary'], dtype='str')

In [89]:
print(df.isnull().sum())

Name       0
 Age       0
Email      0
Country    0
Salary     1
dtype: int64

In [90]:
print(df)

    Name  Age             Email  Country  Salary
0  Isaac    17  isaac@email.com    Ghana  2000.0
1   John         john@email.com      USA  3000.0
2   mary    25   MARY@email.com       uk     NaN
4  Kodjo    30     noemail@.com  Nigeria  4000.0
5  Peter   200      peter@email    Kenya  5000.0
6   Anna    22   anna@email.com           3500.0
7  Kwame   28   kwame@email.com    Ghana  5300.0

In [91]:
df.loc[2,"Salary"] = 7356
print(df)

    Name  Age             Email  Country  Salary
0  Isaac    17  isaac@email.com    Ghana  2000.0
1   John         john@email.com      USA  3000.0
2   mary    25   MARY@email.com       uk  7356.0
4  Kodjo    30     noemail@.com  Nigeria  4000.0
5  Peter   200      peter@email    Kenya  5000.0
6   Anna    22   anna@email.com           3500.0
7  Kwame   28   kwame@email.com    Ghana  5300.0

In [24]:
print(df.isnull())

    Name   Age   Email  Country  Salary
0  False  False  False    False   False
1  False  False  False    False   False
2  False  False  False    False   False
4  False  False  False    False   False
5  False  False  False    False   False
6  False  False  False    False   False
7  False  False  False    False   False

In [25]:
df.dtypes

Name           str
 Age           str
Email          str
Country        str
Salary     float64
dtype: object

In [26]:
print(df)

    Name  Age             Email  Country  Salary
0  Isaac    17  isaac@email.com    Ghana  2000.0
1   John         john@email.com      USA  3000.0
2   mary    25   MARY@email.com       uk  7356.0
4  Kodjo    30     noemail@.com  Nigeria  4000.0
5  Peter   200      peter@email    Kenya  5000.0
6   Anna    22   anna@email.com           3500.0
7  Kwame   28   kwame@email.com    Ghana  5300.0

In [27]:
df.loc[6,"Country"] = "Uganda"

In [28]:
print(df)

    Name  Age             Email  Country  Salary
0  Isaac    17  isaac@email.com    Ghana  2000.0
1   John         john@email.com      USA  3000.0
2   mary    25   MARY@email.com       uk  7356.0
4  Kodjo    30     noemail@.com  Nigeria  4000.0
5  Peter   200      peter@email    Kenya  5000.0
6   Anna    22   anna@email.com   Uganda  3500.0
7  Kwame   28   kwame@email.com    Ghana  5300.0

In [29]:
df.dtypes

Name           str
 Age           str
Email          str
Country        str
Salary     float64
dtype: object

In [30]:
df[" Age "] = df[" Age "].str.strip()

In [31]:
print(df)

    Name  Age             Email  Country  Salary
0  Isaac    17  isaac@email.com    Ghana  2000.0
1   John         john@email.com      USA  3000.0
2   mary    25   MARY@email.com       uk  7356.0
4  Kodjo    30     noemail@.com  Nigeria  4000.0
5  Peter   200      peter@email    Kenya  5000.0
6   Anna    22   anna@email.com   Uganda  3500.0
7  Kwame    28  kwame@email.com    Ghana  5300.0

In [32]:
print(df.columns)

Index(['Name', ' Age ', 'Email', 'Country', 'Salary'], dtype='str')

In [33]:
df.columns = df.columns.str.strip()

In [34]:
print(df)

    Name  Age            Email  Country  Salary
0  Isaac   17  isaac@email.com    Ghana  2000.0
1   John        john@email.com      USA  3000.0
2   mary   25   MARY@email.com       uk  7356.0
4  Kodjo   30     noemail@.com  Nigeria  4000.0
5  Peter  200      peter@email    Kenya  5000.0
6   Anna   22   anna@email.com   Uganda  3500.0
7  Kwame   28  kwame@email.com    Ghana  5300.0

In [35]:
print(df.columns)

Index(['Name', 'Age', 'Email', 'Country', 'Salary'], dtype='str')

In [36]:
df["Age"] = pd.to_numeric(df["Age"],errors="coerce")

In [37]:
print(df)

    Name    Age            Email  Country  Salary
0  Isaac   17.0  isaac@email.com    Ghana  2000.0
1   John    NaN   john@email.com      USA  3000.0
2   mary   25.0   MARY@email.com       uk  7356.0
4  Kodjo   30.0     noemail@.com  Nigeria  4000.0
5  Peter  200.0      peter@email    Kenya  5000.0
6   Anna   22.0   anna@email.com   Uganda  3500.0
7  Kwame   28.0  kwame@email.com    Ghana  5300.0

In [38]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [39]:
print(df)

    Name    Age            Email  Country  Salary
0  Isaac   17.0  isaac@email.com    Ghana  2000.0
1   John   26.5   john@email.com      USA  3000.0
2   mary   25.0   MARY@email.com       uk  7356.0
4  Kodjo   30.0     noemail@.com  Nigeria  4000.0
5  Peter  200.0      peter@email    Kenya  5000.0
6   Anna   22.0   anna@email.com   Uganda  3500.0
7  Kwame   28.0  kwame@email.com    Ghana  5300.0

In [40]:
df.loc[5,"Age"] = 25

In [41]:
print(df)

    Name   Age            Email  Country  Salary
0  Isaac  17.0  isaac@email.com    Ghana  2000.0
1   John  26.5   john@email.com      USA  3000.0
2   mary  25.0   MARY@email.com       uk  7356.0
4  Kodjo  30.0     noemail@.com  Nigeria  4000.0
5  Peter  25.0      peter@email    Kenya  5000.0
6   Anna  22.0   anna@email.com   Uganda  3500.0
7  Kwame  28.0  kwame@email.com    Ghana  5300.0

In [42]:
df.loc[2, "Email"] = "mary@email.com"
df.loc[4, "Email"] = "noemail@email.com"
df.loc[5, "Email"] = "peter@email.com"

In [43]:
print(df)

    Name   Age              Email  Country  Salary
0  Isaac  17.0    isaac@email.com    Ghana  2000.0
1   John  26.5     john@email.com      USA  3000.0
2   mary  25.0     mary@email.com       uk  7356.0
4  Kodjo  30.0  noemail@email.com  Nigeria  4000.0
5  Peter  25.0    peter@email.com    Kenya  5000.0
6   Anna  22.0     anna@email.com   Uganda  3500.0
7  Kwame  28.0    kwame@email.com    Ghana  5300.0

In [44]:
df.dtypes

Name           str
Age        float64
Email          str
Country        str
Salary     float64
dtype: object

In [45]:
df["Age"] = df["Age"].astype(int)

In [46]:
df.dtypes

Name           str
Age          int64
Email          str
Country        str
Salary     float64
dtype: object

In [47]:
print(df
)

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   mary   25     mary@email.com       uk  7356.0
4  Kodjo   30  noemail@email.com  Nigeria  4000.0
5  Peter   25    peter@email.com    Kenya  5000.0
6   Anna   22     anna@email.com   Uganda  3500.0
7  Kwame   28    kwame@email.com    Ghana  5300.0

In [48]:
df.head()

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   mary   25     mary@email.com       uk  7356.0
4  Kodjo   30  noemail@email.com  Nigeria  4000.0
5  Peter   25    peter@email.com    Kenya  5000.0

In [49]:
df.head()

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   mary   25     mary@email.com       uk  7356.0
4  Kodjo   30  noemail@email.com  Nigeria  4000.0
5  Peter   25    peter@email.com    Kenya  5000.0

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 7
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     7 non-null      str
 1   Age      7 non-null      int64
 2   Email    7 non-null      str
 3   Country  7 non-null      str
 4   Salary   7 non-null      float64
dtypes: float64(1), int64(1), str(3)
memory usage: 636.0 bytes

In [51]:
pd.melt(df)

   variable              value
0      Name              Isaac
1      Name               John
2      Name               mary
3      Name              Kodjo
4      Name              Peter
5      Name               Anna
6      Name              Kwame
7       Age                 17
8       Age                 26
9       Age                 25
10      Age                 30
11      Age                 25
12      Age                 22
13      Age                 28
14    Email    isaac@email.com
15    Email     john@email.com
16    Email     mary@email.com
17    Email  noemail@email.com
18    Email    peter@email.com
19    Email     anna@email.com
20    Email    kwame@email.com
21  Country              Ghana
22  Country                USA
23  Country                 uk
24  Country            Nigeria
25  Country              Kenya
26  Country             Uganda
27  Country              Ghana
28   Salary             2000.0
29   Salary             3000.0
30   Salary             7356.0
31   Salary             4000.0
32   Salary             5000.0
33   Salary             3500.0
34   Salary             5300.0

In [52]:
df.pivot(index="Name", columns="Age", values="Email")

Age,17,22,25,26,28,30
Name,,,,,,
Anna,NaN,anna@email.com,NaN,NaN,NaN,NaN
Isaac,isaac@email.com,NaN,NaN,NaN,NaN,NaN
John,NaN,NaN,NaN,john@email.com,NaN,NaN
Kodjo,NaN,NaN,NaN,NaN,NaN,noemail@email.com
Kwame,NaN,NaN,NaN,NaN,kwame@email.com,NaN
Peter,NaN,NaN,peter@email.com,NaN,NaN,NaN
mary,NaN,NaN,mary@email.com,NaN,NaN,NaN

In [53]:
df.pivot(index="Name", columns="Country", values="Salary")

Country   Ghana   Kenya  Nigeria     USA  Uganda      uk
Name
Anna        NaN     NaN      NaN     NaN  3500.0     NaN
Isaac    2000.0     NaN      NaN     NaN     NaN     NaN
John        NaN     NaN      NaN  3000.0     NaN     NaN
Kodjo       NaN     NaN   4000.0     NaN     NaN     NaN
Kwame    5300.0     NaN      NaN     NaN     NaN     NaN
Peter       NaN  5000.0      NaN     NaN     NaN     NaN
mary        NaN     NaN      NaN     NaN     NaN  7356.0

In [54]:
df.describe()

             Age       Salary
count   7.000000     7.000000
mean   24.714286  4308.000000
std     4.231402  1757.777384
min    17.000000  2000.000000
25%    23.500000  3250.000000
50%    25.000000  4000.000000
75%    27.000000  5150.000000
max    30.000000  7356.000000

In [55]:
df["Age"].mean()

np.float64(24.714285714285715)

In [56]:
df["Salary"].max()

np.float64(7356.0)

In [57]:
df["Name"].value_counts()

Name
Isaac    1
John     1
mary     1
Kodjo    1
Peter    1
Anna     1
Kwame    1
Name: count, dtype: int64

In [58]:
print(df)

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   mary   25     mary@email.com       uk  7356.0
4  Kodjo   30  noemail@email.com  Nigeria  4000.0
5  Peter   25    peter@email.com    Kenya  5000.0
6   Anna   22     anna@email.com   Uganda  3500.0
7  Kwame   28    kwame@email.com    Ghana  5300.0

In [59]:
df.columns

Index(['Name', 'Age', 'Email', 'Country', 'Salary'], dtype='str')

In [60]:
df["Email"] = df["Email"].str.strip()

In [61]:
print(df)

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   mary   25     mary@email.com       uk  7356.0
4  Kodjo   30  noemail@email.com  Nigeria  4000.0
5  Peter   25    peter@email.com    Kenya  5000.0
6   Anna   22     anna@email.com   Uganda  3500.0
7  Kwame   28    kwame@email.com    Ghana  5300.0

In [62]:
df["Name"] = df["Name"].str.title()

In [63]:
print(df)

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   Mary   25     mary@email.com       uk  7356.0
4  Kodjo   30  noemail@email.com  Nigeria  4000.0
5  Peter   25    peter@email.com    Kenya  5000.0
6   Anna   22     anna@email.com   Uganda  3500.0
7  Kwame   28    kwame@email.com    Ghana  5300.0

In [64]:
df = df.reset_index(drop=True)

In [65]:
print(df)

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    Ghana  2000.0
1   John   26     john@email.com      USA  3000.0
2   Mary   25     mary@email.com       uk  7356.0
3  Kodjo   30  noemail@email.com  Nigeria  4000.0
4  Peter   25    peter@email.com    Kenya  5000.0
5   Anna   22     anna@email.com   Uganda  3500.0
6  Kwame   28    kwame@email.com    Ghana  5300.0

In [66]:
df["Country"] = df["Country"].str.upper()

In [67]:
df.head()

    Name  Age              Email  Country  Salary
0  Isaac   17    isaac@email.com    GHANA  2000.0
1   John   26     john@email.com      USA  3000.0
2   Mary   25     mary@email.com       UK  7356.0
3  Kodjo   30  noemail@email.com  NIGERIA  4000.0
4  Peter   25    peter@email.com    KENYA  5000.0

In [68]:
df.to_csv("format_clean",index=False)